### ISSUE TITLE
Robo-melpazoid

### ISSUE THREAD

**Issue by dickmao** [melpa/melpa#7454]
I could spruce up the github action piece to fire off a melpazoid instance.  This, I can only imagine, would asynchronize the pipeline both from melpa's and the prospective contributor's perspectives.  Please let me know if that's a "yeah, no thanks" thing (as most of my suggestions https://github.com/melpa/package-build/pull/32 seem to result in that response https://github.com/purcell/package-lint/pull/193).  Peace.

Cc: @riscy

**Comment by riscy** [comment]
Closely related is this issue and comment, I think: https://github.com/melpa/melpa/issues/6714#issuecomment-589462922 -- not to close your issue too quickly, but maybe it would be better to continue this discussion there?  (I'll be happy to respond there too with my perspective.)

I think we do want something like this, and I'll leave a quick couple of notes here.  Beyond the checklist checks, some of the checks I've stuffed into melpazoid are a bit fast and loose and raise false positives that require a human filter, so some small adaptation would be required.  Also, some perfectly valid packages can't be accurately checked by melpazoid because they depend on packages like vterm or mu4e with nontrivial installs, and which I haven't gone to the trouble of installing in melpazoid's docker image.  These sorts of issues are becoming less and less common, but something to note.

A related approach I've been playing with is to add a comment-bot to MELPA.  With GitHub actions it seems to be as simple as:
```yaml
name: comment-bot

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!check')
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --request POST \
          --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments' \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "body": "Heard a comment from ${{ github.actor }} on #${{ github.event.issue.number }}."
          }'

```
so that if anyone includes the string `!check` in a PR's comment, a workflow could run and post the output.  A drawback with the above implementation is that it leaves a lot of "cancelled" workflows in the actions log, since the `if` is checked only after the job starts.
